[workspace]
members = ["crates/oxislam-features", "crates/oxislam-geometry", "crates/oxislam-image"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Cliff Yuan Li <dev@cliff.li>"]
license = "MIT"
repository = "https://github.com/cyuanli/oxislam"
