edition = "2024"
style_edition = "2024"

unstable_features = true
fn_single_line = true

group_imports = "StdExternalCrate"
imports_granularity = "Module"

use_field_init_shorthand = true

max_width = 100

use_small_heuristics = "Max"

merge_derives = false
